POST http://127.0.0.1:8000/api/log
Content-Type: application/json

{
    "version": "Versija 55",
    "file": "something.bin"
}

###

GET http://127.0.0.1:8000/api/log
Content-Type: application/json

###
